### ISSUE TITLE
Can't connect to server (BotStudio)

### ISSUE THREAD

**Issue by jorgehtml** [botcity-dev/botcity-framework-core-python#24]
I am trying to make my login in the BotStudio.exe, but every time i try to do this, this error shows up and i can't fix this, somebody can help?
![image](https://user-images.githubusercontent.com/78984109/185426021-96ec4b32-4325-4671-9ff2-44be6b5dd81b.png)
![image](https://user-images.githubusercontent.com/78984109/185426046-a67fc8f5-f894-4b5c-b701-9ad5c536b907.png)

**Comment by hhslepicka** [comment]
Hi @jorgehtml,
Please try to follow the instructions on how to test your SDK first with the BotCLI [available here](https://documentation.botcity.dev/getting-started/botcity-studio-sdk/#testing-your-botcity-studio-sdk).

If you can successfully run the test and use your e-mail and password to access the BotCity Maestro, it is likely that your system is blocking the BotStudio binary from reaching the BotCity Maestro service. In this case, please check your firewall configuration.

You can get faster help with BotCity Studio via Slack with our community. [Click here to access BotCity Community Slack](https://join.slack.com/t/communitybotcitydev/shared_invite/zt-xt5lu9bq-l2E1gcf9pZgr4UrnIRJMLw).

**Comment by jorgehtml** [comment]
Yes, I think it is... might my firewall is blocking the app, do you know how can i turn off or allow the application on firewall?

**Comment by hhslepicka** [comment]
@jorgehtml you can do a quick test by disabling your firewall completely and re-enabling it later on https://www.lifewire.com/how-to-disable-the-windows-firewall-2624505

If you have an antivirus solution that could also be acting up and blocking the connection.

**Note:** Disabling your firewall completely can create risks to your computer. I recommend you check the proper way to add BotStudio and other tools as exceptions to rules or allow them to connect with the internet instead of disabling. The recommendation to disable is just for a quick test.

**Comment by hhslepicka** [comment]
Closing the issue as the conversation moved to Slack: https://communitybotcitydev.slack.com/archives/C02K76QCC0M/p1660843338813679
